/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrintAntrian;

import java.awt.print.PrinterException;
import java.util.logging.Level; 
import java.util.logging.Logger;


public class DialogPrint extends javax.swing.JFrame {

    private int antrian_umum = 1;
    private int antrian_KIA = 1;
    private int antrian_Mtbs = 1;
    private int antrian_Lansia = 1;
    private String jenis;
    public DialogPrint() {
        initComponents();
        IdAntrianUmum.setText(Integer.toString(antrian_umum));
        IdAntrianKia.setText(Integer.toString(antrian_KIA));
        IdAntrianMtbs.setText(Integer.toString(antrian_Mtbs));
        IdAntrianLansia.setText(Integer.toString(antrian_Lansia));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_print_umum = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IdAntrianUmum = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Button_print_KIA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IdAntrianKia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Button_print_mtbs = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        IdAntrianMtbs = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Button_print_lansia = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        IdAntrianLansia = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        restart_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_print_umum.setText("print antrian UMUM");
        Button_print_umum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_print_umumActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nomor Antrian");

        IdAntrianUmum.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        IdAntrianUmum.setText("1");

        jLabel2.setText("UMUM");

        Button_print_KIA.setText("print Antrian KIA");
        Button_print_KIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_print_KIAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nomor Antrian");

        IdAntrianKia.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        IdAntrianKia.setText("1");

        jLabel4.setText("KIA");

        Button_print_mtbs.setText("print Antrian MTBS");
        Button_print_mtbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_print_mtbsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Nomor Antrian");

        IdAntrianMtbs.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        IdAntrianMtbs.setText("1");

        jLabel6.setText("MTBS");

        Button_print_lansia.setText("print Antrian Lansia");
        Button_print_lansia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_print_lansiaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Nomor Antrian");

        IdAntrianLansia.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        IdAntrianLansia.setText("1");

        jLabel8.setText("LANSIA");

        jMenu1.setText("Setting");

        restart_menu.setText("restart nomor");
        restart_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_menuActionPerformed(evt);
            }
        });
        jMenu1.add(restart_menu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(IdAntrianUmum)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(Button_print_umum)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(IdAntrianKia)))
                    .addComponent(Button_print_KIA))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(IdAntrianMtbs)))
                    .addComponent(Button_print_mtbs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Button_print_lansia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdAntrianLansia)
                            .addComponent(jLabel8))))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdAntrianLansia)
                        .addGap(52, 52, 52)
                        .addComponent(Button_print_lansia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(IdAntrianMtbs))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(IdAntrianKia)
                        .addGap(50, 50, 50)
                        .addComponent(Button_print_mtbs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(IdAntrianUmum)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_print_umum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_print_KIA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_print_umumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_print_umumActionPerformed
        jenis= "UMUM";
        try {
            Print p = new Print(antrian_umum,jenis);
        } catch (PrinterException ex) {
            Logger.getLogger(DialogPrint.class.getName()).log(Level.SEVERE, null, ex);
        }
        antrian_umum++;
        IdAntrianUmum.setText(Integer.toString(antrian_umum));
    }//GEN-LAST:event_Button_print_umumActionPerformed

    private void restart_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_menuActionPerformed
        antrian_umum = 1;
        antrian_Lansia = 1;
        antrian_Mtbs = 1;
        antrian_KIA =1 ;        
        IdAntrianUmum.setText(Integer.toString(antrian_umum));
        IdAntrianKia.setText(Integer.toString(antrian_KIA));
        IdAntrianMtbs.setText(Integer.toString(antrian_Mtbs));
        IdAntrianLansia.setText(Integer.toString(antrian_umum));
    }//GEN-LAST:event_restart_menuActionPerformed

    private void Button_print_KIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_print_KIAActionPerformed
        jenis= "KIA";
        try {
            Print p = new Print(antrian_KIA,jenis);
        } catch (PrinterException ex) {
            Logger.getLogger(DialogPrint.class.getName()).log(Level.SEVERE, null, ex);
        }
        antrian_KIA++;
        IdAntrianKia.setText(Integer.toString(antrian_KIA));
    }//GEN-LAST:event_Button_print_KIAActionPerformed

    private void Button_print_mtbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_print_mtbsActionPerformed
        jenis= "MTBS";
        try {
            Print p = new Print(antrian_Mtbs,jenis);
        } catch (PrinterException ex) {
            Logger.getLogger(DialogPrint.class.getName()).log(Level.SEVERE, null, ex);
        }
        antrian_Mtbs++;
        IdAntrianMtbs.setText(Integer.toString(antrian_Mtbs));
    }//GEN-LAST:event_Button_print_mtbsActionPerformed

    private void Button_print_lansiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_print_lansiaActionPerformed
        jenis= "LANSIA";
        try {
            Print p = new Print(antrian_Lansia,jenis);
        } catch (PrinterException ex) {
            Logger.getLogger(DialogPrint.class.getName()).log(Level.SEVERE, null, ex);
        }
        antrian_Lansia++;
        IdAntrianLansia.setText(Integer.toString(antrian_Lansia));
    }//GEN-LAST:event_Button_print_lansiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_print_KIA;
    private javax.swing.JButton Button_print_lansia;
    private javax.swing.JButton Button_print_mtbs;
    private javax.swing.JButton Button_print_umum;
    private javax.swing.JLabel IdAntrianKia;
    private javax.swing.JLabel IdAntrianLansia;
    private javax.swing.JLabel IdAntrianMtbs;
    private javax.swing.JLabel IdAntrianUmum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem restart_menu;
    // End of variables declaration//GEN-END:variables
}
